app:
  brokers: "127.0.0.1:9092"

producer:
  returnSuccesses: true
  retryCount: 5
  requiredAcks: -1

topic:
  name: "first_topic"
  keySerializer: "string"
  valueSerializer: "string"

consumer:
  offset: -1

group:
  name: "my-first-group"
  version: 3.0.0
  assignor: "roundrobin"
  oldest: true

